### ISSUE TITLE
DNS for mails cdn

### ISSUE THREAD

**Issue by marcosbermejo** [doctoralia/styleguide#49]
make a CNAME entry:

mails.doctoralia.com -> http://az798749.vo.msecnd.net/

**Comment by daviddiaz** [comment]
si esto es para los componentes relacionados con mails, pondría algo mas especifico. "mail" o "mails" se reserva para temas de correo propiamente dicho.

**Comment by marcosbermejo** [comment]
mail-components.doctoralia.com podría ser?

**Comment by jorditorra** [comment]
El unico motivo era que al ser components en plural, tenia sentido meter
mails en plural. Si quereis una alternativa aqui importa poco, pues que en
los mails haya mas html de la cuenta nos da un poco igual.

**Comment by daviddiaz** [comment]
Mi preferencia sería usar   components-mails.doctoralia.com  de forma que los CNAME queden ordenados teniendo agrupados los que tengan que ver con desarrollo de componentes.

**Comment by jorditorra** [comment]
ok!

*Jordi Torra*
CTO
Josep Pla 2, B2, 08019 Barcelona
www.doctoralia.com

2015-08-14 7:54 GMT+02:00 David <notifications@github.com>:

**Comment by jorditorra** [comment]
David, dále con  components-mails.doctoralia.com -> http://az798749.vo.msecnd.net/ porfa

**Comment by daviddiaz** [comment]
Hecho
